### ISSUE TITLE
Not able to use bootloader.bin on Raspberry Pi 3B

### ISSUE THREAD

**Issue by petemoore** [cs107e/cs107e.github.io#17]
Hi,

Is it known if `bootloader.bin` should work on Raspberry Pi 3B?

I'm able to run other `kernel.img` files using the supplied `start.elf` and `bootcode.bin`, but when I copy `bootloader.bin` to `kernel.img`, I see the ACT LED flash once or twice, but I have the Raspberry PI "rainbow" splash screen via HDMI display. The ACT LED does not continue to flash after the first couple of flashes, so I believe the problem lies on the RPi side of the bootloader process, rather than from the client that initiates the kernel upload.

My SD card drive looks like this:

```
$ md5 /Volumes/RPI/*
MD5 (/Volumes/RPI/bootcode.bin) = fd01b240fcc5d4c83560676415081508
MD5 (/Volumes/RPI/kernel.img) = 9cd7bb9062f8c77dc47610794fde0163
MD5 (/Volumes/RPI/start.elf) = cf4b634e9e6eb2dab81b4c2d94eb5ff6
```

I experimented by adding a `config.txt` file with the single entry `enable_uart=1` to see if this would resolve the issue, but alas it did not seem to change the behaviour in any noticeable way.

Replacing `kernel.img` with [this `kernel7.img` file](https://github.com/PeterLemon/RaspberryPi/blob/7130e72637d08b1976512bd60a372acb9b458310/NEON/Fractal/Mandelbrot/kernel7.img?raw=true) and adding [this `config.txt` file](https://raw.githubusercontent.com/PeterLemon/RaspberryPi/51cd75567235ff1782961a9acc31d0e1fc006432/boot/config.txt) worked for me, suggesting that `bootcode.bin` and `start.elf` are working fine, and the SD card is properly formatted etc. This is how the root directory looked in this successful arrangement:

```
$ md5 /Volumes/RPI/*
MD5 (/Volumes/RPI/bootcode.bin) = fd01b240fcc5d4c83560676415081508
MD5 (/Volumes/RPI/config.txt) = 34d4125b8f0b6d0b78afdaa9f163cba9
MD5 (/Volumes/RPI/kernel7.img) = a297d606caf1ff1cb45902f489bd8641
MD5 (/Volumes/RPI/start.elf) = cf4b634e9e6eb2dab81b4c2d94eb5ff6
```

As you see, I have taken the `bootcode.bin` and `start.elf` from the cs107e `firmware` folder and simply added the `config.txt` and `kernel7.img` from Peter Lemon's repository. I share this simply to demonstrate that the Raspberry Pi 3B indeed functions correctly and can boot a custom kernel on the SD card I created.

Note, the output I see from the client side is:

```
Found serial port: /dev/cu.SLAB_USBtoUART
Sending `/Users/pmoore/RPiDev/kernel.img` (460 bytes): xxxxxx
./rpi-install.py: Send failed (bootloader not listening?)

I waited a few seconds for an acknowledgement from the bootloader
and didn't hear anything. Do you need to reset your Pi?

Further help at http://cs107e.github.io/guides/bootloader/#troubleshooting

```

Many thanks in advance, and I hope this may help others that hit the same problem! :-)

**Comment by phanrahan** [comment]
All our code has only tested on the Raspberry Pi 1 A+. It should also work on the Pi 1 B+.

It is unlikely to work on the Pi 2 and Pi 3. Those are different chips with different memory maps, etc. 

If you want a bootloader for those systems, I suggest you visit dwelch's raspberry pi repo. He has code for different versions of the Pi.
