### ISSUE TITLE
Kit inventory specifications

### ISSUE THREAD

**Issue by ElasticBottle** [cs107e/cs107e.github.io#19]
Hi,

Will you be able to advise on the part specifications/ where to get these parts?

In particular, I'm interested in the USB to serial breakout board. Is there a specific model or place where I can get a similar copy? I have only found boards with female micro usb to vcc, ID, D+, D-, and ground breakouts. 

Other than that, if I wish to follow along the curriculum, the other parts should be able to work even if sourced elsewhere and have no specific model dependencies? (Other than BJT and raspberry pi which from the other issues, I understand to be a pi 1 A+)

Thank you so much for your time and I hope this helps those trying to follow along this interesting and exciting looking class on their own!

**Comment by phanrahan** [comment]
We use a CP2102 USB 2.0 to TTL UART 6PIN.

https://www.taydaelectronics.com/bte13-007-cp2102-serial-converter-usb-2-0-to-ttl-uart-ftdi.html

I bought the ones we use on ebay and it cost about $1.

Almost any usb-serial breakout board will work. But the instructions are written for this once. The pictures will match, and the driver setup should be accurate.

Good luck

**Comment by ElasticBottle** [comment]
Thank you so much!
