### ISSUE TITLE
Lab 1 exercise 9, possible error?

### ISSUE THREAD

**Issue by ElasticBottle** [cs107e/cs107e.github.io#20]
Hi, 

I noticed that under exercise _9. Add a button! (optional)_ in **Lab 1** the comment for branching was that the LEV register for the input button goes LOW after pressing it. At that point, the code branches to on:
```
beq on // when the button is pressed (goes LOW), turn on LED
```
However, upon looking at the prior code, it is noted that the branching to on only happens when there's a 1 in the position of the input pin's LEV register, or HIGH.
```
// read GPIO 10 
    ldr r0, LEV0
    ldr r1, [r0] 
    tst r1, r2 // r2 has value #(1 << 10)
```
In that case, wouldn't the LED be on whenever the button is not pressed? 

Am I missing or misunderstanding something? Any and all clarifications will be greatly appreciated!

Warmest Regards,
ElasticBottle

**Comment by zelenski** [comment]
The `tst` instruction is bitwise AND (will set flags) and is followed by a `beq` which conditionally executes if zero flag is set. Together these instructions takes branch only when level is low.

**Comment by ElasticBottle** [comment]
That clears things up so much, thank you!
