### ISSUE TITLE
Could you please provide a public link for downloading starter files?

### ISSUE THREAD

**Issue by cj1128** [cs107e/cs107e.github.io#21]
First, I want to say that I have always been interested in OS and low-level stuff and this course is just amazing and awesome!

I am a software engineer in China and I enjoy so much self-studying this course when I am off work.

But since I am not an official student I can't get access to the starter files of each assignment.  So I want to know can you provide a public link for downloading these materials? It will be a great help for people like me to self-study this excellent course.

**Comment by harryhan618** [comment]
I think you can find all the header files in `cs107e/include/*.h`. The API is very clear. Just implement the rest yourself.

**Comment by cj1128** [comment]
That is an option. But it would be much better if I can get the same starter files mentioned in the tutorial.
